### ISSUE TITLE
Patch for /trunk/psicquic-webservice/src/example/python/read-all-psicquic.py

### ISSUE THREAD

**Issue by noedelta** [PSICQUIC/psicquic-webservice#1]
_From @GoogleCodeExporter on March 18, 2015 11:1_

```
I update the libraries used, Instead urllib2 I used requests and for XML 
parsing ElementTree
```

Original issue reported on code.google.com by `gunzap...@gmail.com` on 6 May 2014 at 1:09

Attachments:
- [read-all-psicquic.py.patch](https://storage.googleapis.com/google-code-attachments/psicquic/issue-35/comment-0/read-all-psicquic.py.patch)

_Copied from original issue: MICommunity/psicquic#35_

**Comment by noedelta** [comment]
_From @GoogleCodeExporter on March 18, 2015 11:1_

```
Hi,
Psicquic is very handsome, A wonderful thing!

The library used for xml parsing are out of date. I first correct it using 
ElementTree. 

In a second time I chose to use requests instead of urllib2, because it is more 
intuitive and "pythonic".

Thank again for the service
Pietro Brunetti

```

Original comment by `gunzap...@gmail.com` on 6 May 2014 at 1:16

**Comment by bblodfon** [comment]
I have updated the python code and its pretty much the same as this user proposed.
