### ISSUE TITLE
Patch for /trunk/psicquic-webservice/src/example/perl/read-all-psicquic.pl

### ISSUE THREAD

**Issue by noedelta** [PSICQUIC/psicquic-webservice#4]
_From @GoogleCodeExporter on March 18, 2015 11:1_

```
I hink it's an error.
```

Original issue reported on code.google.com by `spaqu...@gmail.com` on 3 Jul 2012 at 9:19

Attachments:
- [read-all-psicquic.pl.patch](https://storage.googleapis.com/google-code-attachments/psicquic/issue-30/comment-0/read-all-psicquic.pl.patch)

_Copied from original issue: MICommunity/psicquic#30_

**Comment by bblodfon** [comment]
No, its not. Perl example works fine as it is. Applying the patch results in error actually.
